// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trvddvelcbdoagzrogpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydmRkdmVsY2Jkb2FnenJvZ3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDc3NjksImV4cCI6MjA3MTk4Mzc2OX0.zttNF_xzh6_3L6Z5Ah8EqsBtDZpJOt4VxGRDtJOUef8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});